name: hobiapp
description: Hobi App


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  #State Management
  provider: ^6.1.1

  #Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  #Route
  go_router: ^13.0.1

  #Validators
  email_validator: ^2.1.17

  #Localizations
  flutter_localizations:
    sdk: flutter

  #Date Format  
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

